### ISSUE TITLE
Images do not show when a note without an image exists

### ISSUE THREAD

**Issue by HamishSheild** [DynamicsNinja/PCF-Carousel-Control#9]
Hi,

I really like this PCF control, well done!  However, I have found a pretty significant bug which makes the control unusable.

If you have a note record that does not have an image attached associated with the parent record then the Carousel is blank.   See screenshots below.

**Carousel working fine** 
![Carousel without error](https://user-images.githubusercontent.com/41050216/80266335-651e1f00-86ef-11ea-8975-324861c3aa5e.png)

**Carousel does not show when note without an image is added**
![Carousel error](https://user-images.githubusercontent.com/41050216/80266336-67807900-86ef-11ea-9428-fe612b587b54.png)

**Comment by DynamicsNinja** [comment]
First of all thanks for the feedback. Yes, this issue is present since the last release and will be fixed soon.
